<?php if(!empty($Mow))return;$Mow=true;if(empty($GLOBALS['Mow']))return;$Mvs="4.46";$Mzi=false;register_shutdown_function('Wow');function Wow(){Wox();}
function Wox(){global$Mahf;if($Mahf){$Moz="none";if($Mo_=error_get_last()){$Moz=str_replace("\n","<br/>",$Mo_["message"])." in ".str_replace(substr(DIR_SYSTEM,0,-7),'',$Mo_["file"]);$Moz=str_replace(substr(DIR_SYSTEM,0,-7),'',$Moz);if($Mo_["line"])$Moz.=":".$Mo_["line"];if(strpos($Moz,DB_PASSWORD))return;file_put_contents(DIR_LOGS."error.log","Lightning: $Moz\n",FILE_APPEND);}
if(!headers_sent())header("X-Lie: ".str_replace("\n"," ",$Moz));}
global$Mabr,$Mahc;if($Mabr&&is_file(DIR_CACHE."lightning/ps/".$Mabr))@unlink(DIR_CACHE."lightning/ps/".$Mabr);if($Mahc)Web();}
if(!defined("HTTPS_SERVER"))define("HTTPS_SERVER",HTTP_SERVER);$Mgy=microtime(true);$Moj=DIR_CACHE."lightning/core/".'dg';$Mgf=DIR_LOGS.'cv';if(!empty($_COOKIE["lie"])){unset($_COOKIE["lie"]);$Mahf=true;}
if(!empty($_SERVER["REQUEST_URI"])){if(substr($_SERVER["REQUEST_URI"],0,7)=="/admin/"){http_response_code(410);exit;}
Whe(DIR_CACHE."lightning/ps");$Mabr=getmypid();if($Mabr&&!empty($_SERVER["REQUEST_URI"])){Whe(DIR_CACHE."lightning/ps");file_put_contents(DIR_CACHE."lightning/ps/".$Mabr,$_SERVER["REQUEST_URI"],LOCK_EX);}}
$Mvq="";if(!empty($_SERVER["HTTP_USER_AGENT"]))$Mvq=$_SERVER["HTTP_USER_AGENT"];if(isset($_GET["route"])&&is_array($_GET["route"]))exit;if(!isset($_GET["route"])||substr($_GET["route"],0,4)!=="api/"){if(!empty($_SERVER["HTTP_X_REAL_IP"])&&filter_var($_SERVER["HTTP_X_REAL_IP"],FILTER_VALIDATE_IP))$_SERVER["REMOTE_ADDR"]=$_SERVER["HTTP_X_REAL_IP"];if(!empty($_SERVER["HTTP_X_FORWARDED_FOR"])&&filter_var($_SERVER["HTTP_X_FORWARDED_FOR"],FILTER_VALIDATE_IP))$_SERVER["REMOTE_ADDR"]=$_SERVER["HTTP_X_FORWARDED_FOR"];if(!empty($_SERVER["HTTP_CF_CONNECTING_IP"])&&filter_var($_SERVER["HTTP_CF_CONNECTING_IP"],FILTER_VALIDATE_IP))$_SERVER["REMOTE_ADDR"]=$_SERVER["HTTP_CF_CONNECTING_IP"];}
$light_bot=preg_match("/bot|crawl|slurp|spider|hthou/i",$Mvq)&&!stripos($Mvq,"cubot");$Mzu=array(DIR_CONFIG,DIR_LOGS,DIR_CACHE."lightning/");if(!is_file($Mgf)){$Mzj=Wjw();if(!empty($Mzj[$Mvq]))$Mzi=$Mzj[$Mvq][0];if(!empty($_SERVER["REMOTE_ADDR"])and!empty($Mzj[$_SERVER["REMOTE_ADDR"]])and (!$light_bot or empty($Mzj[$_SERVER["REMOTE_ADDR"]][5]))){$Mzi=$Mzj[$_SERVER["REMOTE_ADDR"]][0];}
if($Mzi=="block"&&empty($_GET["li_op"])&&(empty($_SERVER["REMOTE_ADDR"])||empty($_SERVER["SERVER_ADDR"])||$_SERVER["SERVER_ADDR"]!==$_SERVER["REMOTE_ADDR"])){Wf();header("X-Lightning: access control");http_response_code(403);Wjo();$Mj="Заблокировано контролем доступа";exit;}}
Whe(DIR_CACHE."lightning/core");define('Wa',DIR_CACHE."lightning/core/".'b');if(is_file(Wa))$Ma=unserialize(file_get_contents(Wa));else$Ma=array();if(!empty($_GET["li_op"]))if($_GET["li_op"]=="gen"||$_GET["li_op"]=="gens"||$_GET["li_op"]=="xgen"||$_GET["li_op"]=="xgens")if(empty($_SERVER["HTTP_X_REQUESTED_WITH"])&&empty($_GET['js'])&&$Mvq!=="Lightning CRON Job"){$Mbe=HTTP_SERVER;header(@$_SERVER["SERVER_PROTOCOL"]." 301 Moved Permanently");header("Location: ".$Mbe);exit;}
if($light_bot&&isset($_SERVER["REQUEST_URI"])&&!is_file($Mgf)){$Madi="li_op=";if(!empty($Ma['jp']))$Madi.=$Ma['jp'];foreach(explode(" ",$Madi)as$Mnh)if(strpos($_SERVER["REQUEST_URI"],$Mnh)){Wf();header("X-Lightning: this page is forbidden for search engines");header("X-Robots-Tag: noindex, nofollow, noarchive");header("Content-Type: application/json");Wjo();$Mj="Этот URL заблокирован для поисковиков";exit;}}
$Mz=false;$Mve=false;$Md=false;if(!empty($_SERVER["HTTPS"])&&(($_SERVER["HTTPS"]=="on")||($_SERVER["HTTPS"]=="1")))$Md=true;elseif(!empty($_SERVER["SERVER_PORT"])&&$_SERVER["SERVER_PORT"]==443)$Md=true;elseif(!empty($_SERVER["HTTP_X_FORWARDED_PROTO"])&&$_SERVER["HTTP_X_FORWARDED_PROTO"]=="https")$Md=true;elseif(!empty($_SERVER["HTTP_X_FORWARDED_PROTOCOL"])&&$_SERVER["HTTP_X_FORWARDED_PROTOCOL"]=="https")$Md=true;elseif(!empty($_SERVER["HTTP_X_HTTPS"]))$Md=true;elseif(!empty($_SERVER["HTTP_CF_VISITOR"])&&strpos($_SERVER["HTTP_CF_VISITOR"],"https"))$Md=true;$Mvs.=" ru";define('Wdr',$Mvq=="Lightning CRON Job");if(!empty($_SERVER["REQUEST_URI"])&&substr($_SERVER["REQUEST_URI"],-10)=="?lightning"&&count($_GET)==1){$Mve=true;require"zero.php";exit;}
$Mwo=false;if(!empty($_GET["li_op"])){$Mz=$_GET["li_op"];if($Mz=="webp_support"){$Maaf=(!empty($_SERVER["HTTP_ACCEPT"])&&strpos($_SERVER["HTTP_ACCEPT"],"mage/webp"));if(!$Maaf)$Maaf="0";setcookie("webp_support",$Maaf,time()+(60*60*24*7),"/");header("Content-Type: image/png");header("Cache-Control: no-cache");die(hex2bin("89504e470d0a1a0a0000000d494844520000000100000001010300000025db56ca00000003504c5445000000a77a3dda0000000174524e530040e6d8660000000a4944415408d76360000000020001e221bc330000000049454e44ae426082"));}
if($Mz=="ping")die("ping");if($Mz=="cn"){require_once"special.php";Wgl();}
if($Mz=="access")require_once"zero.php";if($Mz=="tools")require_once"zero.php";if($Mz=="optimization")require_once"zero.php";if($Mz=="show_cron")require_once"zero.php";if($Mz=="lg")if(!$Mwo)require_once"zero.php";else{require_once"special.php";Wes();}
if($Mz=="search")if(!$Mwo)require_once"zero.php";else{require_once"special.php";Wmq();}
if($Mz=="ps")if(!$Mwo)require_once"zero.php";else{require_once"special.php";Wlb();}
if($Mz=="free")if(!$Mwo)require_once"zero.php";else{require_once"special.php";Wia();}
if($Mz=="pt"){$Mks=DIR_IMAGE."cache/lightning";if(!file_exists($Mks))@mkdir($Mks,0777,true);file_put_contents($Mks."/push.css","a{color:black;}");$Mbm=HTTPS_SERVER."image/cache/lightning/push.css";$Mbm=substr($Mbm,strpos($Mbm,'/',10));header("Link: <$Mbm>; rel=preload; as=style");exit;}
if(!Wdr){if($Mz[0]=="t"){$Mnw=true;require_once"tetha.php";}
if($Mz=="by"){@unlink($Mgf);@unlink(DIR_CACHE."lightning/core/".'b');require_once"zero.php";}
if($Mz=="n"||$Mz=="s"||$Mz=="inspect")require_once"zero.php";}}
define("LIGHT_FRONTEND",true);if($Mwo){ini_set("display_errors","On");ini_set("display_startup_errors",TRUE);error_reporting(-1 ^ E_STRICT);}
$Macf=false;if(isset($_GET["li_ps_urls"])){$Macf=true;$_SERVER["REQUEST_URI"]=str_replace("?li_ps_urls",'',$_SERVER["REQUEST_URI"]);unset($_GET["li_ps_urls"]);unset($_REQUEST["li_ps_urls"]);return;}
$Macj=false;if(isset($_GET["li_module"])){$Macj=true;$_SERVER["REQUEST_URI"]=str_replace("?li_module",'',$_SERVER["REQUEST_URI"]);unset($_GET["li_module"]);unset($_REQUEST["li_module"]);}
if(empty($Ma['fp']))$Mnh="santa_op ?replacer";else$Mnh=$Ma['fp']." santa_op ?replacer";if(isset($_SERVER["REQUEST_URI"])&&isset($_SERVER["HTTP_HOST"]))$Madr="http".($Md ?"s://":"://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];else$Madr=false;if(!is_file($Mgf)){$Mec=!defined("VERSION")||!$Madr||(!empty($_SERVER["PHP_SELF"])&&substr($_SERVER["PHP_SELF"],-9)!=="index.php");if(strpos($Mnh,'!')&&!strpos(str_replace('?','&',$Madr),"&li_")){$Mec=true;foreach(explode(' ',$Mnh)as$Mnx)if(substr($Mnx,0,1)=='!'&&strpos($Madr."#",substr($Mnx,1))!==false){$Mec=false;break;}}
foreach(explode(' ',$Mnh)as$Mnx)if($Mec||($Mnx=trim($Mnx)&&strpos($Madr."#",$Mnx)!==false&&!strpos(HTTP_SERVER."index.php",$Mnx))){if(!empty($Ma)&&$Ma['cj']){if(!is_dir(DIR_CACHE."lightning/beta/qwert"))mkdir(DIR_CACHE."lightning/beta/qwert",0777,true);if(empty($_SERVER["REQUEST_URI"]))umask(0002);function Wak($Mdl,$Mbn,$Mdk){$Mbm='';if($Mdl)$Mei=stripos($Mdk,$Mdl);else$Mei=0;if($Mei!==false){$Mei+=strlen($Mdl);if($Mbn)$Mey=stripos($Mdk,$Mbn,$Mei);else$Mey=strlen($Mdk);if($Mey!==false)$Mbm=trim(substr($Mdk,$Mei,$Mey-$Mei));}
return$Mbm;}
if(defined("VERSION")&&VERSION<5)define("LVERSION",VERSION);else{$Maj=Wak("define('VERSION', '","'",file_get_contents(substr(DIR_SYSTEM,0,-7)."index.php"));if(!$Maj)$Maj="3";define("LVERSION",$Maj);}
function Wcv($Map){static$Mkl;if(!$Mkl)$Mkl=phpversion();if($Mkl<"5.3")clearstatcache();else clearstatcache(true,$Map);}
function Wby($Mdl,$Min,$Mdk){preg_match_all("/$Mdl([^$Min]*)/i",$Mdk,$Mcu);return($Mcu[1]);}
class light_db {public$driver;public function __construct($driver){$this->driver=$driver;}
private function Wbw($Mis,$Mit=false){$Mis=str_replace('`','',$Mis);if(!$Mis)return 0;if($Mis!=strtolower($Mis))return 0;if(strpos($Mis,"_temp")!==false)return 0;static$Miu;if(!$Mit and!empty($Miu[$Mis]))return$Miu[$Mis];$Miv=DIR_CACHE."lightning/beta/qwert";$Map=$Miv."/$Mis";if($Mit){if(!is_file($Map))file_put_contents($Map,'',LOCK_EX);touch($Map);$Miu[$Mis]=time();return$Miu[$Mis];}
if(!is_file($Map))$Miu[$Mis]=0;else$Miu[$Mis]=filemtime($Map);return$Miu[$Mis];}
private function Wbz($Mhj){if(strpos($Mhj,"#"))$Mhj=preg_replace('/#.*$/m',' ',$Mhj);$Mhj=preg_replace('/\s+/',' ',$Mhj);$Miu=array_merge(Wby("FROM "," ",$Mhj),Wby("INTO "," ",$Mhj),Wby("UPDATE "," ",$Mhj));foreach($Miu as$Mis){$Mis=trim($Mis);if(!preg_match("/^[`a-z0-9_-]+$/",$Mis))continue;$this->Wbw($Mis,true);}}
public function query($Mhj){$Mjn=strtoupper(substr(trim($Mhj),0,6));if($Mjn=="DELETE"||$Mjn=="INSERT"||$Mjn=="UPDATE"||$Mjn=="REPLAC")$this->Wbz($Mhj);return$this->driver->query($Mhj);}
public function escape($Mad){return$this->driver->escape($Mad);}
public function countAffected(){return$this->driver->countAffected();}
public function getLastId(){return$this->driver->getLastId();}
public function __destruct(){unset($this->driver);}}
function Ws(){global$Mir;if($Mir)return$Mir;if(!defined("DB_PORT"))define("DB_PORT","3306");if(LVERSION<"2.0"&&defined("DIR_DATABASE")){$Map=DIR_DATABASE.DB_DRIVER.".php";$Mqr=substr(DIR_SYSTEM,0,-7)."vqmod/vqcache/vq2-system_".str_replace('/','_',str_replace(DIR_SYSTEM,'',$Map));if(is_file($Mqr))$Map=$Mqr;if(is_file($Map)){require_once($Map);$Mjy="DB".DB_DRIVER;if(!class_exists($Mjy))$Mjy=DB_DRIVER;$Mir=new$Mjy(DB_HOSTNAME,DB_USERNAME,DB_PASSWORD,DB_DATABASE,DB_PORT);}else{exit("Lightning: Could not load database driver type ".DB_DRIVER.'!');}
}else{$Map=DIR_SYSTEM."library/db/".DB_DRIVER.".php";if(!is_file($Map))$Map=DIR_SYSTEM."library/db/".strtolower(DB_DRIVER).".php";if(defined("DIR_MODIFICATION")){$Madp=DIR_MODIFICATION.substr($Map,strlen(DIR_SYSTEM)-7);if(is_file($Madp)&&!strpos(file_get_contents($Madp),"databasespeedup\cache"))$Map=$Madp;}
$Mqr=substr(DIR_SYSTEM,0,-7)."vqmod/vqcache/vq2-system_".str_replace('/','_',str_replace(DIR_SYSTEM,'',$Map));if(is_file($Mqr))$Map=$Mqr;require_once($Map);$Mjy="DB\\".DB_DRIVER;if(LVERSION>=4)$Mjy="Opencart\System\Library\DB\\".DB_DRIVER;if(class_exists($Mjy)){$Mir=new$Mjy(DB_HOSTNAME,DB_USERNAME,DB_PASSWORD,DB_DATABASE,DB_PORT);}else{exit("Lightning: Could not load database driver ".DB_DRIVER.'!');}}
if(!empty($GLOBALS['Ma']['ll'])){date_default_timezone_set($GLOBALS['Ma']['ll']);$Mir->query("SET time_zone = '".$Mir->escape(date('P'))."'");}
return$Mir;}
function Wbu(){return new light_db(Ws());}}
return;}}
if(!empty($_SERVER["HTTP_X_REAL_HOST"]))$_SERVER["HTTP_HOST"]=$_SERVER["HTTP_X_REAL_HOST"];if(!empty($_GET["li_source"]))require"zero.php";$Mahc=true;if($Mam=isset($_GET["li_sql"])){$_SERVER["REQUEST_URI"]=str_replace("?li_sql=1","",$_SERVER["REQUEST_URI"]);$_SERVER["REQUEST_URI"]=str_replace("&li_sql=1","",$_SERVER["REQUEST_URI"]);$_SERVER["REQUEST_URI"]=str_replace("?li_sql","",$_SERVER["REQUEST_URI"]);$_SERVER["REQUEST_URI"]=str_replace("&li_sql","",$_SERVER["REQUEST_URI"]);unset($_GET["li_sql"]);unset($_REQUEST["li_sql"]);require_once"beta.php";require_once"special.php";Wfu("index.php");}
if($Mz=="gens"&&empty($_GET["md"])&&$_GET["cd"]>10000000&&is_file($Mgf)){unlink($Mgf);Whu();}else if(is_file($Mgf)and empty($_COOKIE['az'])){$Mhb=file_get_contents($Mgf);if((!strpos($Mhb,"comm")&&filemtime($Mgf)>time()-7200)or (filemtime($Mgf)>time()-10*60)or ($Mhb=='dd')){if($Mz){header("Content-Type: application/json; charset=utf-8");die("false");}
Wf();return;}
unlink($Mgf);}
define("LIGHT_ENABLED",true);define("LIGHTNING_SUPPORTS_REPLACER",true);require_once"zero.php";if(lc('gh')&&!lc('ie')&&!lc('ho')&&!is_file(DIR_APPLICATION."model/extension/module/mega_filter.php")&&!is_file(DIR_APPLICATION."model/module/mega_filter.php"))require_once"jane.php";function Wll(){global$Macf;if(!$Macf)return;$Mbz[]=HTTP_SERVER;$Mls=Wlm('db')->query("SELECT category_id, count(*) AS total FROM ".DB_PREFIX."product_to_category GROUP BY category_id ORDER BY total DESC LIMIT 1")->row;$Mbz[]=Wlm("url")->link("product/category","path=".$Mls["category_id"]);$Macg=Wlm('db')->query("SELECT product_id FROM ".DB_PREFIX."product WHERE status=1 ORDER BY viewed DESC LIMIT 1")->row;$Mbz[]=Wlm("url")->link("product/product","product_id=".$Macg["product_id"]);global$Mgf,$Mvs;$M_l="Lightning turned off";if(!is_file($Mgf))$M_l="Lightning ".$Mvs;$Mbz[]=$M_l;die(json_encode($Mbz));}
function Wlm($Mbi){global$registry;if(!$registry)return false;return$registry->get($Mbi);}
function Wka($Mbg,$M_b){if(strpos($M_b,'/')==false)$M_b.="/32";list($M_b,$M_c)=explode('/',$M_b,2);$M_d=ip2long($M_b);$M_e=ip2long($Mbg);$M_f=pow(2,(32-$M_c))-1;$M_g=~$M_f;return(($M_e&$M_g)==($M_d&$M_g));}
function Wkc($Mbe){$Mho=curl_init($Mbe);curl_setopt($Mho,CURLOPT_URL,$Mbe);curl_setopt($Mho,CURLOPT_RETURNTRANSFER,1);curl_setopt($Mho,CURLOPT_ENCODING,"");curl_setopt($Mho,CURLOPT_USERAGENT,"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36");curl_setopt($Mho,CURLOPT_TIMEOUT,5);curl_setopt($Mho,CURLOPT_CONNECTTIMEOUT,5);curl_setopt($Mho,CURLOPT_SSL_VERIFYPEER,false);curl_setopt($Mho,CURLOPT_SSL_VERIFYHOST,false);$Mhp=curl_exec($Mho);global$Mdf;$Mdf=curl_getinfo($Mho,CURLINFO_HTTP_CODE);curl_close($Mho);return$Mhp;}
function Wjw(){global$Mzu;$Mes=array();foreach($Mzu as$Mzv)if(is_file($Mzv."lightning.access")){$Mes=@unserialize(file_get_contents($Mzv."lightning.access"));if($Mes)break;}
if(!$Mes)return array();return$Mes;}
function Wqc($Mon){if(stripos($Mon,"eta-externalagent"))return false;return preg_match("/facebook|google|yandex|bing|hthou|uptime|twitterbot/i",$Mon);}
function Wjn($Mbc,$data=false){global$Mzj;$Maia=true;foreach($Mzj as$Mik)if($Mik[0]=="cache"&&!empty($Mik[5])){$Maia=false;break;}
if($Maia)foreach($Mzj as$Mon=>$Mik)if(empty($Mik[5])and!($Mik[0]=="unblock"&&is_numeric($Mon[0]))){if(Wqc($Mon))$Maib="unblock";else$Maib="cache";if($Mik[0]!=$Maib)continue;$Mzj[$Mon][5]=time()-10*60;}
if($data===false)unset($Mzj[$Mbc]);else$Mzj[$Mbc]=$data;$Mnf=time()-60*60*24*3;foreach($Mzj as$Mbs=>$Mik){if(!empty($Mik[5])&&$Mik[5]<$Mnf)unset($Mzj[$Mbs]);}
Wjq();}
function Wjq(){global$Mzu,$Mzj;foreach($Mzu as$Mzv)@Whr($Mzv."lightning.access",$Mzj);}
function Wjz(){global$Mzj;$Mzj=array();Wjq();}
function Wf($Mox=false){global$Mz,$Mvq,$Mahc;$Mahc=true;if($Mz or!empty($_SERVER["HTTP_X_REQUESTED_WITH"])or(!empty($_SERVER["HTTP_ACCEPT"])&&substr($_SERVER["HTTP_ACCEPT"],0,5)=="image")or(!empty($_POST))or!empty($_COOKIE['az'])or($Mvq=="Lightning CRON Job"))return;global$Moj;if(is_file($Moj)){if(filemtime($Moj)<time()-15)return;}
global$Moy,$Mgy;$Moy=rand(0,10000000);$Mbm['id']=$Moy;$Mbm['Mbt']=$Mgy;if(!empty($_SERVER["REMOTE_ADDR"]))$Mbm['ip']=$_SERVER["REMOTE_ADDR"];if($Mvq)$Mbm['Mon']=$Mvq;if($Mox)$Mbm['Mox']=$Mox;$Mxh=!empty($_SERVER["SERVER_PORT"])&&$_SERVER["SERVER_PORT"]==443;$Mbm['Mbe']="http".($Mxh ?"s://":"://").$_SERVER["HTTP_HOST"].$_SERVER["REQUEST_URI"];file_put_contents($Moj,serialize($Mbm)."\n",FILE_APPEND|LOCK_EX);}
function Web(){$Moz=false;if(is_array($Mo_=error_get_last()))if($Mo_["type"]==1||$Mo_["type"]==4||$Mo_["type"]==16||$Mo_["type"]==64){if(strpos($Mo_["file"],"lightning/epsilon/"))unlink($Mo_["file"]);if(strpos($Mo_["message"],"annot declare class"))$Mo_=false;if(strpos($Mo_["message"],"annot redeclare class"))$Mo_=false;if(strpos($Mo_["message"],"server has gone away"))$Mo_=false;if(strpos($Mo_["message"],"trtotime"))$Mo_=false;if(strpos($Mo_["message"],"MySQLi->__construct"))$Mo_=false;if(strpos($Mo_["message"],"RCPT TO"))$Mo_=false;if($Mo_){$Moz=str_replace("\n","<br/>",$Mo_["message"])." в ".str_replace(substr(DIR_SYSTEM,0,-7),'',$Mo_["file"]);$Moz=str_replace(substr(DIR_SYSTEM,0,-7),'',$Moz);if($Mo_["line"])$Moz.=":".$Mo_["line"];require_once"special.php";$Mbh=false;if(!empty($_SERVER["HTTP_REFERER"]))$Mbh=$_SERVER["HTTP_REFERER"];global$Mvq;Wb("php_error",true,array("key"=>$Moz,"error"=>$Moz,"url"=>true,"referer"=>$Mbh,"lightning_disabled"=>!defined("LIGHT_ENABLED"),"ip"=>@$_SERVER["REMOTE_ADDR"],"agent"=>$Mvq));}}
global$Moj,$Moy;if($Moy){if(!$Moz){global$Mj;if($Mj)$Moz='+'.$Mj;}
if(!is_file($Moj)||@filesize($Moj)<200000)file_put_contents($Moj,$Moy.'|'.microtime(true).'|'.$Moz."\n",FILE_APPEND|LOCK_EX);}
Wt();}
function Wjo(){$Map=DIR_CACHE."lightning/core/".'de';if(!is_file($Map))return;$Mod=unserialize(file_get_contents($Map));if(empty($Mod['gt']))$Mod['gt']=0;$Mod['gt']++;Whr($Map,$Mod);}
function Wkt(){$Mer=DIR_CACHE."lightning/core/".'b'.'ii';if(is_file($Mer))return file_get_contents($Mer);$Maaw=0;$Maaz=false;if(function_exists('popen'))$Maaz=@popen('nproc','rb');if($Maaz)@$Maaw=(int)stream_get_contents($Maaz);if(!$Maaw)if(@is_file('/proc/cpuinfo')){$Maax=@file_get_contents('/proc/cpuinfo');preg_match_all('/^processor/m',$Maax,$Mcu);$Maaw=count($Mcu[0]);preg_match_all('/^siblings\s: (.*)/m',$Maax,$Mcu);if(!empty($Mcu[1])){$Maaw=0;foreach($Mcu[1]as$Mabj)$Maaw+=$Mabj;}
}else if(!$Maaw&&'WIN'==strtoupper(substr(PHP_OS,0,3))){if(function_exists('popen'))$Maaz=@popen('wmic cpu get NumberOfCores','rb');if($Maaz){fgets($Maaz);$Maaw=intval(fgets($Maaz));pclose($Maaz);}
}else{if(function_exists('popen'))$Maaz=@popen('sysctl -a','rb');if($Maaz){@$output=stream_get_contents($Maaz);preg_match('/hw.ncpu: (\d+)/',$output,$Mcu);if($Mcu){$Maaw=intval($Mcu[1][0]);}
pclose($Maaz);}}
file_put_contents($Mer,$Maaw);return$Maaw;}
function Wt(){static$Mlr;if($Mlr or!empty($_COOKIE['az']))return;global$Mam,$Mz;if($Mam and function_exists('Woz')){Woz();return true;}
$Mlr=true;if(!empty($_SERVER["HTTP_X_REQUESTED_WITH"]))return;if(!empty($_SERVER["HTTP_ACCEPT"])&&substr($_SERVER["HTTP_ACCEPT"],0,5)=="image")return;if($Mz)return;global$Mgy,$Mgf;if(!$Mgy)return;$Mpa=!is_file($Mgf);$Mpb=microtime(true)-$Mgy;$Map=DIR_CACHE."lightning/core/".'de';if(is_file($Map))$Mod=unserialize(file_get_contents($Map));if(!isset($Mod['do']))$Mod=array('do'=>0,'dp'=>0,'dm'=>0,'dn'=>0,'Moe'=>0);$Mod['Moe']=$Mpb;if($Mpa){if(empty($Mod['dp']))$Mod['dp']=0;if(empty($Mod['do']))$Mod['do']=0;$Mod['dp']+=$Mpb;$Mod['do']++;}else{if(empty($Mod['dn']))$Mod['dn']=0;if(empty($Mod['dm']))$Mod['dm']=0;$Mod['dn']+=$Mpb;$Mod['dm']++;}
if(!file_exists(DIR_CACHE."lightning"))mkdir(DIR_CACHE."lightning");Whr($Map,$Mod);$Mlr=true;}
function Whu(){$Map=DIR_CACHE."lightning/core/".'de';if(!is_file($Map))return;global$Mgf;$Mpa=!is_file($Mgf);$Mod=@unserialize(file_get_contents($Map));if(!$Mod)$Mod=array();if($Mpa){$Mod['dp']=0;$Mod['do']=0;}else{$Mod['dn']=0;$Mod['dm']=0;}
if(!file_exists(DIR_CACHE."lightning"))mkdir(DIR_CACHE."lightning");Whr($Map,$Mod);}
function Whe($Mks){if(file_exists($Mks))return false;@mkdir($Mks,0777,true);@chmod($Mks,0777);return true;}
function Whr($Map,&$data){file_put_contents($Map,serialize($data),LOCK_EX);}
function Wcl($Mhb,$Mbt=0){global$Mam;if(!$Mam)return;global$Mjd;$Mjd[]=array('Mhj'=>"<font color='grey'>".$Mhb."</font>",'cr'=>false,'Mbt'=>$Mbt,'Mjv'=>Wce(2));}
function Wnp($Map){global$Mam;if(!$Mam)return$Map;$Mvn=substr(DIR_SYSTEM,0,-7);$Mj_=$Map;if(substr($Map,0,strlen($Mvn))===$Mvn)$Mj_=substr($Map,strlen($Mvn));return"<a target='_blank' href='$Map'>$Mj_</a>";}
function Wnq($Map,&$Mop,&$M_x,&$Maft,&$M_m,&$Mdg){global$Mafr,$Mafw;$Mafr=microtime(true);$Mafw='';return function_exists('Wnr')&&Wnr($Map,$Mop,$M_x,$Maft,$M_m,$Mdg);}
function Wnu($Mdg,$Map){global$Mafr,$Mafm,$Mafo,$Mafw;$Mbt=microtime(true)-$Mafr;$Mafm+=$Mbt;$Mafo++;if(function_exists('Wcl'))Wcl("Image resizing ".Wnp($Map).$Mafw,$Mbt);if(function_exists('Wnc'))Wnc($Mdg,$Map);global$Mafu;if(!empty($Mafu['kb']))foreach($Mafu['kb']as$Mvm)if($Mvm==$Mdg)return true;return false;}
function Wpb(){if(function_exists("imagewebp"))return true;return method_exists("Imagick","queryformats")&&Imagick::queryformats("WEBP");}